functions:
  'main':
    description: 'This function automatically levels mobs, if they fit certain requirements.'
    linked-events: ['on-mob-spawn', 'on-mob-scan']
    processes:
      - process: 'check-not-levellable'
        description: 'Establishes conditions required for individual mobs to become levelled.'
        if:
          - check: 'world-name'
            description: 'A list of world names which mobs cannot be levelled in.'
            is-in-list: []
            case-sensitivity: true
          - check: 'entity-type'
            description: 'A list of mob entity types which are not allowed to become levelled. Note: you may want to consider nerfing the attribute multipliers on the mob instead of making it not levelled.'
            is-in-list: []
          - check: 'mob-owner'
            description: 'A list of MobOwner plugin integration names which are allowed to become levelled.'
            is-not-in-list: []
        do:
          - action: 'adjust-level'
            description: 'This tells LevelledMobs to not level the mob.'
            set-to: none
          - action: 'exit-function'
            description: 'This tells LevelledMobs to not continue running this function for the mob.'
      - process: 'apply-level'
        do:
          - action: 'set-nametag'
            format: '[%entity-prefix%Lvl.%entity-level% | %entity-name% | %entity-health%/%entity-max-health%hp]'
            visibility-duration: 1
            visibility-methods: ['']
          - action: 'set-rule-inheritance'
            babies-inherit-rules: true
            passengers-inherit-rules: true
        use-presets: ['standard-difficulty']

  'nametag-updater':
    description: 'This function automatically updates the nametags of levelled mobs.'
    linked-events: ['on-mob-damage', 'on-mob-regain-health', 'on-player-join', 'on-player-teleport', 'on-mob-track']
    processes:
      - process: 'update-nametag-for-mob'
        description: 'Update the nametag of the mob'
        if:
          - check: 'levelled-state'
            description: 'Check if the mob is not levelled'
            require-state: false
        do:
          - action: 'update-nametag'

# Do not edit these values!
metadata:
  version:
    original: 999
    current: 999
