##########################################
#           ~ LevelledMobs v4 ~          #
# The Ultimate RPG Mob Levelling Plugin  #
##########################################

functions:
  'main':
    description: 'This function automatically levels mobs, if they fit certain requirements.'
    triggers: ['on-mob-spawn', 'on-mob-scan']
    processes:
      - process: 'check-not-levellable'
        description: 'Establishes conditions required for individual mobs to become levelled.'
        if:
          - check: 'world-name'
            description: 'A list of world names which mobs cannot be levelled in.'
            case-sensitivity: true
            in-list: []
          - check: 'entity-type'
            description: 'A list of mob entity types which are not allowed to become levelled. Note: you may want to consider nerfing the attribute multipliers on the mob instead of making it not levelled.'
            in-list: []
          - check: 'mob-owner'
            description: 'A list of MobOwner plugin integration names which are allowed to become levelled.'
            not-in-list: []
        do:
          - action: 'set-level'
            description: 'This tells LevelledMobs to not level the mob.'
            formula: 'no-level'
          - action: 'exit-function'
            description: 'This tells LevelledMobs to not continue running this function for the mob.'
      - process: 'apply-level'
        do:
          - action: 'set-nametag'
            format: '[%entity-prefix%Lvl.%entity-level% | %entity-name% | %entity-health%/%entity-max-health%hp]'
            visibility-duration: 1
            visibility-methods: ['']
#          - action: 'set-rule-inheritance'
#            babies-inherit-rules: true
#            passengers-inherit-rules: true
##### unsure how rule inheritance would be programmed
##### in an efficient manner. it's likely that we will
##### need to remove the feature entirely.
        use-presets: ['standard-difficulty']

  'nametag-updater':
    description: 'This function automatically updates the nametags of levelled mobs.'
    triggers: ['on-mob-damage', 'on-mob-regain-health', 'on-player-join', 'on-player-teleport', 'on-mob-track']
    processes:
      - process: 'update-nametag-for-mob'
        description: 'Update the nametag of the mob'
        if:
          - check: 'levelled-state'
            description: 'Check if the mob is not levelled'
            required-state: false
        do:
          - action: 'update-nametag'

#### File Metadata
# Do not edit this section!
metadata:
  version:
    original: 999
    current: 999
